[build]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["core"]

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash"
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
]

[alias]
test-hil = [
    "test",
    "--tests",
    "--no-default-features",
    "--config",
    "target.xtensa-esp32s3-none-elf.runner=\"probe-rs run --chip esp32s3\"",
    "--config",
    "target.xtensa-esp32s3-none-elf.rustflags=[\"-C\",\"link-arg=-Tembedded-test.x\"]",
]
