[build]
target = "riscv32imc-unknown-none-elf"

[target.riscv32imc-unknown-none-elf]
runner = "wlink -v flash --enable-sdi-print --watch-serial"

[alias]
test-hil = [
    "test",
    "--tests",
    "--no-default-features",
    "--config",
    "target.riscv32imc-unknown-none-elf.runner=\"probe-rs run --chip CH32V203K8T6\"",
    "--config",
    "target.riscv32imc-unknown-none-elf.rustflags=[\"-C\",\"link-arg=-Tlink.x\",\"-C\",\"link-arg=-Tembedded-test.x\"]",
]
