[package]
name = "dick_mouse"
version = "0.1.0"
edition = "2024"

[features]
default = ["firmware-bin"]
firmware-bin = []

[dependencies]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041", default-features = false }
embassy-futures = { version = "0.1.2", default-features = false }
embassy-sync = { version = "0.8.0", default-features = false }
embassy-time = { version = "0.5.1", default-features = false }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041", default-features = false, features = ["max-interface-count-8", "usbd-hid"] }
esp-backtrace = { version = "0.20.0", default-features = false, features = ["esp32s3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.5.0", default-features = false, features = ["esp32s3"] }
esp-hal = { version = "1.1.2", default-features = false, features = ["esp32s3", "rt", "unstable"] }
esp-println = { version = "0.18.0", default-features = false, features = ["esp32s3", "uart", "critical-section"] }
esp-rtos = { version = "0.3.0", default-features = false, features = ["embassy", "esp32s3"] }
static_cell = { version = "2.1.1", default-features = false }
usbd-hid = { version = "0.10.1", default-features = false }

[dev-dependencies]
embedded-test = { version = "0.7.2", features = ["xtensa-semihosting"] }

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-executor-macros = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-executor-timer-queue = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", rev = "cd7570483a7036f23a9925a339152396bec4c041" }

[lib]
harness = false
test = false

[[bin]]
name = "dick_mouse"
path = "src/main.rs"
test = false
required-features = ["firmware-bin"]

[[test]]
name = "button"
path = "tests/device/button.rs"
harness = false

[[test]]
name = "encoder"
path = "tests/device/encoder.rs"
harness = false

[[test]]
name = "joystick"
path = "tests/device/joystick.rs"
harness = false

[[test]]
name = "microphone"
path = "tests/device/microphone.rs"
harness = false

[[test]]
name = "speaker"
path = "tests/device/speaker.rs"
harness = false

[[test]]
name = "reexports"
path = "tests/reexports.rs"
harness = false

[[test]]
name = "main"
path = "tests/main.rs"
harness = false

[[test]]
name = "tasks"
path = "tests/tasks/mod.rs"
harness = false
