[package]
name = "dick_mouse"
version = "0.1.0"
edition = "2024"

[features]
default = ["firmware-bin"]
firmware-bin = []

[dependencies]
ch32-hal = { git = "https://github.com/ch32-rs/ch32-hal.git", default-features = false, features = ["ch32v203k8t6", "embassy", "memory-x", "rt", "time-driver-tim2"] }
embassy-executor = { version = "0.10.0", default-features = false, features = ["executor-thread", "platform-spin"] }
embassy-futures = { version = "0.1.2", default-features = false }
embassy-sync = { version = "0.8.0", default-features = false }
embassy-time = { version = "0.5.1", default-features = false }
embassy-usb = { version = "0.5.1", default-features = false, features = ["max-interface-count-8", "usbd-hid"] }
panic-halt = "1.0.0"
qingke-rt = "0.7"
usbd-hid = { version = "0.8.2", default-features = false }

[dev-dependencies]
embedded-test = "0.7.2"

[lib]
harness = false
test = false

[[bin]]
name = "dick_mouse"
path = "src/main.rs"
test = false
required-features = ["firmware-bin"]

[[test]]
name = "button"
path = "tests/device/button.rs"
harness = false

[[test]]
name = "encoder"
path = "tests/device/encoder.rs"
harness = false

[[test]]
name = "joystick"
path = "tests/device/joystick.rs"
harness = false

[[test]]
name = "reexports"
path = "tests/reexports.rs"
harness = false

[[test]]
name = "main"
path = "tests/main.rs"
harness = false

[[test]]
name = "tasks"
path = "tests/tasks/mod.rs"
harness = false

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false
strip = false
