[package]
name = "dick_mouse"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-executor = { version = "0.10.0", default-features = false }
embassy-futures = { version = "0.1.2", default-features = false }
embassy-sync = { version = "0.8.0", default-features = false }
embassy-time = { version = "0.5.1", default-features = false }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b", default-features = false, features = ["max-interface-count-8", "usbd-hid"] }
esp-backtrace = { version = "0.19.0", default-features = false, features = ["esp32s3", "panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.5.0", default-features = false, features = ["esp32s3"] }
esp-hal = { version = "1.1.1", default-features = false, features = ["esp32s3", "rt", "unstable"] }
esp-println = { version = "0.17.0", default-features = false, features = ["auto", "esp32s3"] }
esp-rtos = { version = "0.3.0", default-features = false, features = ["embassy", "esp32s3"] }
static_cell = { version = "2.1.1", default-features = false }
usbd-hid = { version = "0.10.1", default-features = false }

[dev-dependencies]
embedded-test = { version = "0.7.2", features = ["xtensa-semihosting"] }

[patch.crates-io]
embassy-futures = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b" }
embassy-time-driver = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", rev = "89f0ce53bb64d827a00fec5222df4e831b6d541b" }

[lib]
harness = false
test = false

[[bin]]
name = "dick_mouse"
path = "src/main.rs"
test = false

[[test]]
name = "button"
path = "tests/input/button.rs"
harness = false

[[test]]
name = "encoder"
path = "tests/input/encoder.rs"
harness = false

[[test]]
name = "main"
harness = false
